clusterName: hoff
endpoint: https://192.168.20.10:6443

talosVersion: v1.12.3
kubernetesVersion: v1.32.0

cniConfig:
  name: none

additionalApiServerCertSans:
  - 192.168.20.10

nodes:
  - hostname: sequoia
    ipAddress: 192.168.20.3
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    patches:
      - "@./patches/sequoia.yaml"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "*"
        dhcp: false
        addresses:
          - 192.168.20.3/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.20.1
        vip:
          ip: 192.168.20.10

  - hostname: cedar
    ipAddress: 192.168.20.4
    installDisk: /dev/sdc
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    patches:
      - "@./patches/cedar.yaml"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "*"
        dhcp: false
        addresses:
          - 192.168.20.4/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.20.1
        vip:
          ip: 192.168.20.10

  - hostname: spruce
    ipAddress: 192.168.20.5
    installDisk: /dev/sdc
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    patches:
      - "@./patches/spruce.yaml"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "*"
        dhcp: false
        addresses:
          - 192.168.20.5/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.20.1
        vip:
          ip: 192.168.20.10

controlPlane:
  patches:
    - "@./patches/controlplane.yaml"

patches:
  - "@./patches/global.yaml"
