apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.17.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  timeout: 10m
  test:
    enabled: false
  values:
    crds:
      enabled: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
