apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:6WJqaynjCkjkRIozZqOWSiXER24/Rnc42c+KAXCKOYsQigT/32Y4eQ==,iv:te2svqqbbdglXWShh8LvJx636SBKMuU3Lj8P/0cfkec=,tag:+3BMGSa328pDGz2R/1W+1A==,type:str]
sops:
    age:
        - recipient: age1lpyn4275vwe8v56xrphdlqap2swunpcplcyjppesafcv4v2dxyqs4mz83h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Wk94am9QZnZVaGlDVGdN
            NnJ3NTMrUjhqRUlzcnFwbHk1ZHFKUENram44CmZyNG1mSXpVZTM4TFpYa0dSOFIw
            S3JRM283RkRLUytFdlFEelVMNEo1TDQKLS0tIFMrVUIwZS9tdXFaR2I0Q0FjVjcw
            UGNLdTlkeElmU3J0M1BTTGlKNjE2MlkKFWQxmyjjN7oWSfPJ8vOtnfqYZSRUUjJV
            56omkzgk4Kp1LiS2vZDl333VqpljIUIbc1suJ8akpYkVwIo5+XlB0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T03:37:19Z"
    mac: ENC[AES256_GCM,data:21xMWhXwplEsQ4pe1NiwCNCVkszRIa7oNzvRb5hsghyKEvB+j/jTBL4NbTJb0KTuoTf22OJxqhnHZbBqUquJkg5O3kOZQXqgeF/hrSA/x+7okEan8mfL4eC+CkWSr9FNx3J1Ny+J6BfzlBzHdDGdx+lFivS7HDQZ7p1/o/DQv6A=,iv:vOzOAkR+Y7Onn0zCDE1NmLbkngr0JSu3DqSviyymf6Q=,tag:0LRMNpRmdb7tkII1B7Rz+w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.1
